-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_PRT_pred\hdlsrc\LSTM_cell\Linear_Layer.vhd
-- Created: 2024-05-08 02:20:48
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Linear_Layer
-- Source Path: LSTM_cell/LSTM_predictor/LSTM_layers/Linear Layer
-- Hierarchy Level: 2
-- Model version: 5.46
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.LSTM_predictor_pkg.ALL;

ENTITY Linear_Layer IS
  PORT( In1                               :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END Linear_Layer;


ARCHITECTURE rtl OF Linear_Layer IS

  -- Signals
  SIGNAL In1_signed                       : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL linear_weights_out1              : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL in1_9                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_9                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_9_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_9           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_8                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_8                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_8_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_8           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_7                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_7                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_7_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_7           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_6                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_6                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_6_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_6           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_5                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_5                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_5_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_5           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_4                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_4                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_4_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_4           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_3                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_3                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_3_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_3           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_2                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_2                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_2_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_2           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_1                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_1                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_1_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_1           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in1_0                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in2_0                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL mul_Dot_Product_dotp_0_mul_temp  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL tmp_Dot_Product_dotp_0           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sum_Dot_Product_dotp_1           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sum_Dot_Product_dotp_2           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sum_Dot_Product_dotp_3           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sum_Dot_Product_dotp_4           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sum_Dot_Product_dotp_5           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sum_Dot_Product_dotp_6           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sum_Dot_Product_dotp_7           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sum_Dot_Product_dotp_8           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL out1_1                           : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  In1_signed <= In1;

  linear_weights_out1(0) <= to_signed(-16#1EF6#, 16);
  linear_weights_out1(1) <= to_signed(-16#31B3#, 16);
  linear_weights_out1(2) <= to_signed(-16#22BE#, 16);
  linear_weights_out1(3) <= to_signed(16#2A96#, 16);
  linear_weights_out1(4) <= to_signed(-16#2941#, 16);
  linear_weights_out1(5) <= to_signed(16#339C#, 16);
  linear_weights_out1(6) <= to_signed(16#2E92#, 16);
  linear_weights_out1(7) <= to_signed(-16#1FB1#, 16);
  linear_weights_out1(8) <= to_signed(16#3C0B#, 16);
  linear_weights_out1(9) <= to_signed(16#173A#, 16);

  in1_9 <= linear_weights_out1(9);

  in2_9 <= signed(In1_signed(9));

  mul_Dot_Product_dotp_9_mul_temp <= in1_9 * in2_9;
  tmp_Dot_Product_dotp_9 <= mul_Dot_Product_dotp_9_mul_temp(30 DOWNTO 15);

  in1_8 <= linear_weights_out1(8);

  in2_8 <= signed(In1_signed(8));

  mul_Dot_Product_dotp_8_mul_temp <= in1_8 * in2_8;
  tmp_Dot_Product_dotp_8 <= mul_Dot_Product_dotp_8_mul_temp(30 DOWNTO 15);

  in1_7 <= linear_weights_out1(7);

  in2_7 <= signed(In1_signed(7));

  mul_Dot_Product_dotp_7_mul_temp <= in1_7 * in2_7;
  tmp_Dot_Product_dotp_7 <= mul_Dot_Product_dotp_7_mul_temp(30 DOWNTO 15);

  in1_6 <= linear_weights_out1(6);

  in2_6 <= signed(In1_signed(6));

  mul_Dot_Product_dotp_6_mul_temp <= in1_6 * in2_6;
  tmp_Dot_Product_dotp_6 <= mul_Dot_Product_dotp_6_mul_temp(30 DOWNTO 15);

  in1_5 <= linear_weights_out1(5);

  in2_5 <= signed(In1_signed(5));

  mul_Dot_Product_dotp_5_mul_temp <= in1_5 * in2_5;
  tmp_Dot_Product_dotp_5 <= mul_Dot_Product_dotp_5_mul_temp(30 DOWNTO 15);

  in1_4 <= linear_weights_out1(4);

  in2_4 <= signed(In1_signed(4));

  mul_Dot_Product_dotp_4_mul_temp <= in1_4 * in2_4;
  tmp_Dot_Product_dotp_4 <= mul_Dot_Product_dotp_4_mul_temp(30 DOWNTO 15);

  in1_3 <= linear_weights_out1(3);

  in2_3 <= signed(In1_signed(3));

  mul_Dot_Product_dotp_3_mul_temp <= in1_3 * in2_3;
  tmp_Dot_Product_dotp_3 <= mul_Dot_Product_dotp_3_mul_temp(30 DOWNTO 15);

  in1_2 <= linear_weights_out1(2);

  in2_2 <= signed(In1_signed(2));

  mul_Dot_Product_dotp_2_mul_temp <= in1_2 * in2_2;
  tmp_Dot_Product_dotp_2 <= mul_Dot_Product_dotp_2_mul_temp(30 DOWNTO 15);

  in1_1 <= linear_weights_out1(1);

  in2_1 <= signed(In1_signed(1));

  mul_Dot_Product_dotp_1_mul_temp <= in1_1 * in2_1;
  tmp_Dot_Product_dotp_1 <= mul_Dot_Product_dotp_1_mul_temp(30 DOWNTO 15);

  in1_0 <= linear_weights_out1(0);

  in2_0 <= signed(In1_signed(0));

  mul_Dot_Product_dotp_0_mul_temp <= in1_0 * in2_0;
  tmp_Dot_Product_dotp_0 <= mul_Dot_Product_dotp_0_mul_temp(30 DOWNTO 15);

  sum_Dot_Product_dotp_1 <= tmp_Dot_Product_dotp_1 + tmp_Dot_Product_dotp_0;

  sum_Dot_Product_dotp_2 <= tmp_Dot_Product_dotp_2 + sum_Dot_Product_dotp_1;

  sum_Dot_Product_dotp_3 <= tmp_Dot_Product_dotp_3 + sum_Dot_Product_dotp_2;

  sum_Dot_Product_dotp_4 <= tmp_Dot_Product_dotp_4 + sum_Dot_Product_dotp_3;

  sum_Dot_Product_dotp_5 <= tmp_Dot_Product_dotp_5 + sum_Dot_Product_dotp_4;

  sum_Dot_Product_dotp_6 <= tmp_Dot_Product_dotp_6 + sum_Dot_Product_dotp_5;

  sum_Dot_Product_dotp_7 <= tmp_Dot_Product_dotp_7 + sum_Dot_Product_dotp_6;

  sum_Dot_Product_dotp_8 <= tmp_Dot_Product_dotp_8 + sum_Dot_Product_dotp_7;

  out1_1 <= tmp_Dot_Product_dotp_9 + sum_Dot_Product_dotp_8;

  Out1 <= std_logic_vector(out1_1);

END rtl;

