-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_PRT_pred\hdlsrc\LSTM_cell\LSTM_predictor.vhd
-- Created: 2024-05-08 02:20:48
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- out_rsvd                      ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LSTM_predictor
-- Source Path: LSTM_cell/LSTM_predictor
-- Hierarchy Level: 0
-- Model version: 5.46
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.LSTM_predictor_pkg.ALL;

ENTITY LSTM_predictor IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        x_t                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        ce_out                            :   OUT   std_logic;
        out_rsvd                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END LSTM_predictor;


ARCHITECTURE rtl OF LSTM_predictor IS

  -- Component Declarations
  COMPONENT LSTM_layers
    PORT( c_t_1                           :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
          h_t_1                           :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
          x_t                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          out_rsvd                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          c_t                             :   OUT   vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
          h_t                             :   OUT   vector_of_std_logic_vector16(0 TO 9)  -- sfix16_En15 [10]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : LSTM_layers
    USE ENTITY work.LSTM_layers(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Delay_ctrl_const_out             : std_logic;
  SIGNAL Delay_ctrl_delay_out             : std_logic;
  SIGNAL Delay_Initial_Val_out            : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL Delay1_ctrl_const_out            : std_logic;
  SIGNAL Delay1_ctrl_delay_out            : std_logic;
  SIGNAL Delay1_Initial_Val_out           : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL LSTM_layers_out3                 : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL LSTM_layers_out3_signed          : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL Delay1_out                       : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL Delay1_out1                      : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL Delay1_out1_1                    : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL LSTM_layers_out2                 : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL LSTM_layers_out2_signed          : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL Delay_out                        : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL Delay_out1                       : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL Delay_out1_1                     : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL LSTM_layers_out1                 : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_LSTM_layers : LSTM_layers
    PORT MAP( c_t_1 => Delay_out1_1,  -- sfix16_En15 [10]
              h_t_1 => Delay1_out1_1,  -- sfix16_En15 [10]
              x_t => x_t,  -- sfix16_En15
              out_rsvd => LSTM_layers_out1,  -- sfix16_En15
              c_t => LSTM_layers_out2,  -- sfix16_En15 [10]
              h_t => LSTM_layers_out3  -- sfix16_En15 [10]
              );

  Delay_ctrl_const_out <= '1';

  enb <= clk_enable;

  Delay_ctrl_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_ctrl_delay_out <= '0';
      ELSIF enb = '1' THEN
        Delay_ctrl_delay_out <= Delay_ctrl_const_out;
      END IF;
    END IF;
  END PROCESS Delay_ctrl_delay_process;


  Delay_Initial_Val_out(0) <= to_signed(16#1457#, 16);
  Delay_Initial_Val_out(1) <= to_signed(-16#13D3#, 16);
  Delay_Initial_Val_out(2) <= to_signed(16#007B#, 16);
  Delay_Initial_Val_out(3) <= to_signed(16#101E#, 16);
  Delay_Initial_Val_out(4) <= to_signed(16#1FA5#, 16);
  Delay_Initial_Val_out(5) <= to_signed(16#252E#, 16);
  Delay_Initial_Val_out(6) <= to_signed(16#03D3#, 16);
  Delay_Initial_Val_out(7) <= to_signed(-16#1D41#, 16);
  Delay_Initial_Val_out(8) <= to_signed(-16#1C64#, 16);
  Delay_Initial_Val_out(9) <= to_signed(-16#13A1#, 16);

  Delay1_ctrl_const_out <= '1';

  Delay1_ctrl_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_ctrl_delay_out <= '0';
      ELSIF enb = '1' THEN
        Delay1_ctrl_delay_out <= Delay1_ctrl_const_out;
      END IF;
    END IF;
  END PROCESS Delay1_ctrl_delay_process;


  Delay1_Initial_Val_out(0) <= to_signed(16#1B95#, 16);
  Delay1_Initial_Val_out(1) <= to_signed(-16#13E4#, 16);
  Delay1_Initial_Val_out(2) <= to_signed(16#1971#, 16);
  Delay1_Initial_Val_out(3) <= to_signed(-16#14C3#, 16);
  Delay1_Initial_Val_out(4) <= to_signed(16#22C0#, 16);
  Delay1_Initial_Val_out(5) <= to_signed(-16#0C25#, 16);
  Delay1_Initial_Val_out(6) <= to_signed(-16#1890#, 16);
  Delay1_Initial_Val_out(7) <= to_signed(-16#1427#, 16);
  Delay1_Initial_Val_out(8) <= to_signed(16#0965#, 16);
  Delay1_Initial_Val_out(9) <= to_signed(-16#022A#, 16);

  outputgen3: FOR k IN 0 TO 9 GENERATE
    LSTM_layers_out3_signed(k) <= signed(LSTM_layers_out3(k));
  END GENERATE;

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out <= (OTHERS => to_signed(16#0000#, 16));
      ELSIF enb = '1' THEN
        Delay1_out <= LSTM_layers_out3_signed;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  
  Delay1_out1 <= Delay1_Initial_Val_out WHEN Delay1_ctrl_delay_out = '0' ELSE
      Delay1_out;

  outputgen2: FOR k IN 0 TO 9 GENERATE
    Delay1_out1_1(k) <= std_logic_vector(Delay1_out1(k));
  END GENERATE;

  outputgen1: FOR k IN 0 TO 9 GENERATE
    LSTM_layers_out2_signed(k) <= signed(LSTM_layers_out2(k));
  END GENERATE;

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_out <= (OTHERS => to_signed(16#0000#, 16));
      ELSIF enb = '1' THEN
        Delay_out <= LSTM_layers_out2_signed;
      END IF;
    END IF;
  END PROCESS Delay_process;


  
  Delay_out1 <= Delay_Initial_Val_out WHEN Delay_ctrl_delay_out = '0' ELSE
      Delay_out;

  outputgen: FOR k IN 0 TO 9 GENERATE
    Delay_out1_1(k) <= std_logic_vector(Delay_out1(k));
  END GENERATE;

  ce_out <= clk_enable;

  out_rsvd <= LSTM_layers_out1;

END rtl;

