-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_PRT_pred\hdlsrc\LSTM_cell\LSTM_layers.vhd
-- Created: 2024-05-08 02:20:48
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LSTM_layers
-- Source Path: LSTM_cell/LSTM_predictor/LSTM_layers
-- Hierarchy Level: 1
-- Model version: 5.46
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.LSTM_predictor_pkg.ALL;

ENTITY LSTM_layers IS
  PORT( c_t_1                             :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
        h_t_1                             :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
        x_t                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        out_rsvd                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        c_t                               :   OUT   vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
        h_t                               :   OUT   vector_of_std_logic_vector16(0 TO 9)  -- sfix16_En15 [10]
        );
END LSTM_layers;


ARCHITECTURE rtl OF LSTM_layers IS

  -- Component Declarations
  COMPONENT lstm_cell_subsystem
    PORT( c_t_1                           :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
          h_t_1                           :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
          x_t                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          h_t                             :   OUT   vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
          c_t                             :   OUT   vector_of_std_logic_vector16(0 TO 9)  -- sfix16_En15 [10]
          );
  END COMPONENT;

  COMPONENT Linear_Layer
    PORT( In1                             :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : lstm_cell_subsystem
    USE ENTITY work.lstm_cell_subsystem(rtl);

  FOR ALL : Linear_Layer
    USE ENTITY work.Linear_Layer(rtl);

  -- Signals
  SIGNAL lstm_cell_subsystem_out1         : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL lstm_cell_subsystem_out2         : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL Linear_Layer_out1                : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_lstm_cell_subsystem : lstm_cell_subsystem
    PORT MAP( c_t_1 => c_t_1,  -- sfix16_En15 [10]
              h_t_1 => h_t_1,  -- sfix16_En15 [10]
              x_t => x_t,  -- sfix16_En15
              h_t => lstm_cell_subsystem_out1,  -- sfix16_En15 [10]
              c_t => lstm_cell_subsystem_out2  -- sfix16_En15 [10]
              );

  u_Linear_Layer : Linear_Layer
    PORT MAP( In1 => lstm_cell_subsystem_out1,  -- sfix16_En15 [10]
              Out1 => Linear_Layer_out1  -- sfix16_En15
              );

  out_rsvd <= Linear_Layer_out1;

  c_t <= lstm_cell_subsystem_out2;

  h_t <= lstm_cell_subsystem_out1;

END rtl;

