-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_PRT_pred\hdlsrc\LSTM_cell\sig_block1.vhd
-- Created: 2024-05-08 02:20:48
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sig_block1
-- Source Path: LSTM_cell/LSTM_predictor/LSTM_layers/lstm_cell_subsystem/output_gate/sig
-- Hierarchy Level: 4
-- Model version: 5.46
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.LSTM_predictor_pkg.ALL;

ENTITY sig_block1 IS
  PORT( In1                               :   IN    vector_of_std_logic_vector16(0 TO 9);  -- sfix16_En15 [10]
        Out1                              :   OUT   vector_of_std_logic_vector16(0 TO 9)  -- sfix16_En15 [10]
        );
END sig_block1;


ARCHITECTURE rtl OF sig_block1 IS

  -- Component Declarations
  COMPONENT DirectLUTSubNetwork_block2
    PORT( Q1                              :   IN    vector_of_std_logic_vector5(0 TO 9);  -- ufix5 [10]
          fQ1                             :   OUT   vector_of_std_logic_vector16(0 TO 9)  -- sfix16_En15 [10]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : DirectLUTSubNetwork_block2
    USE ENTITY work.DirectLUTSubNetwork_block2(rtl);

  -- Signals
  SIGNAL In1_signed                       : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL In1_0                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k                 : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp          : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_1        : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast          : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp          : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast              : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp          : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast          : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp          : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_1        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_1        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_1            : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index1            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction1         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_1                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_1               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_2        : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_3        : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_2        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_2        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_2            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_1        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_1        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_1        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_3        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_3        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_3            : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index2            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction2         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_2                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_2               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_4        : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_5        : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_4        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_4        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_4            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_2        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_2        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_2        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_5        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_5        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_5            : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index3            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction3         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_3                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_3               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_6        : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_7        : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_6        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_6        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_6            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_3        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_3        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_3        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_7        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_7        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_7            : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index4            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction4         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_4                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_4               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_8        : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_9        : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_8        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_8        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_8            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_4        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_4        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_4        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_9        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_9        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_9            : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index5            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction5         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_5                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_5               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_10       : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_11       : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_10       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_10       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_10           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_5        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_5        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_5        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_11       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_11       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_11           : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index6            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction6         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_6                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_6               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_12       : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_13       : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_12       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_12       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_12           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_6        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_6        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_6        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_13       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_13       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_13           : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index7            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction7         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_7                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_7               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_14       : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_15       : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_14       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_14       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_14           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_7        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_7        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_7        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_15       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_15       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_15           : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index8            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction8         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_8                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_8               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_16       : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_17       : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_16       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_16       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_16           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_8        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_8        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_8        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_17       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_17       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_17           : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index9            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction9         : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL In1_9                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_k_9               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_div_temp_18       : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL prelookup_comp_div_temp_19       : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL prelookup_comp_sub_cast_18       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_sub_temp_18       : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL prelookup_comp_cast_18           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_mul_temp_9        : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL prelookup_comp_add_cast_9        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_add_temp_9        : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL prelookup_comp_sub_cast_19       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_sub_temp_19       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL prelookup_comp_cast_19           : signed(47 DOWNTO 0);  -- sfix48_En47
  SIGNAL prelookup_comp_index10           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_comp_fraction10        : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL prelookup_idx_sat                : vector_of_unsigned5(0 TO 9);  -- ufix5 [10]
  SIGNAL prelookup_idx                    : vector_of_unsigned5(0 TO 9);  -- ufix5 [10]
  SIGNAL prelookup_idx_1                  : vector_of_std_logic_vector5(0 TO 9);  -- ufix5 [10]
  SIGNAL interp_11                        : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL interp_11_signed                 : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL relopout_0                       : std_logic_vector(9 DOWNTO 0);  -- boolean [10]
  SIGNAL relopout_0_0                     : std_logic;
  SIGNAL bias                             : std_logic;  -- ufix1
  SIGNAL adder_v                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q2_plus_one12                    : vector_of_unsigned5(0 TO 9);  -- ufix5 [10]
  SIGNAL Q2_plus_one12_0                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_1                     : std_logic;
  SIGNAL Q2_plus_one12_1                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_2                     : std_logic;
  SIGNAL Q2_plus_one12_2                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_3                     : std_logic;
  SIGNAL Q2_plus_one12_3                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_4                     : std_logic;
  SIGNAL Q2_plus_one12_4                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_5                     : std_logic;
  SIGNAL Q2_plus_one12_5                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_6                     : std_logic;
  SIGNAL Q2_plus_one12_6                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_7                     : std_logic;
  SIGNAL Q2_plus_one12_7                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_8                     : std_logic;
  SIGNAL Q2_plus_one12_8                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL relopout_0_9                     : std_logic;
  SIGNAL Q2_plus_one12_9                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_0                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_0                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_1_1                : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_1                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_2                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_2                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_3                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_3                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_4                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_4                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_5                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_5                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_6                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_6                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_7                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_7                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_8                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_8                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL prelookup_idx_9                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12_9                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Q12                              : vector_of_unsigned5(0 TO 9);  -- ufix5 [10]
  SIGNAL Q12_10                           : vector_of_std_logic_vector5(0 TO 9);  -- ufix5 [10]
  SIGNAL interp_12                        : vector_of_std_logic_vector16(0 TO 9);  -- ufix16 [10]
  SIGNAL interp_12_signed                 : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL fQ2_minus_fQ1_sub_cast           : vector_of_signed17(0 TO 9);  -- sfix17_En15 [10]
  SIGNAL fQ2_minus_fQ1_sub_cast_1         : vector_of_signed17(0 TO 9);  -- sfix17_En15 [10]
  SIGNAL interval                         : vector_of_signed17(0 TO 9);  -- sfix17_En15 [10]
  SIGNAL fraction_idx                     : vector_of_unsigned32(0 TO 9);  -- ufix32_En32 [10]
  SIGNAL interval_times_frac_cast         : vector_of_signed33(0 TO 9);  -- sfix33_En32 [10]
  SIGNAL interval_times_frac_mul_temp     : vector_of_signed50(0 TO 9);  -- sfix50_En47 [10]
  SIGNAL interval_times_frac_cast_1       : vector_of_signed49(0 TO 9);  -- sfix49_En47 [10]
  SIGNAL interp                           : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]
  SIGNAL ReplicaOfSource_out1             : vector_of_signed16(0 TO 9);  -- sfix16_En15 [10]

BEGIN
  u_DirectLUTSubNetwork1_inst : DirectLUTSubNetwork_block2
    PORT MAP( Q1 => prelookup_idx_1,  -- ufix5 [10]
              fQ1 => interp_11  -- sfix16_En15 [10]
              );

  u_DirectLUTSubNetwork2_inst : DirectLUTSubNetwork_block2
    PORT MAP( Q1 => Q12_10,  -- ufix5 [10]
              fQ1 => interp_12  -- sfix16_En15 [10]
              );

  In1_signed <= In1;

  In1_0 <= signed(In1_signed(0));

  prelookup_comp_sub_cast <= resize(In1_0, 17);
  prelookup_comp_sub_temp <= prelookup_comp_sub_cast - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp <= prelookup_comp_sub_temp / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k <= to_unsigned(16#00#, 5) WHEN In1_0 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_0 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp(4 DOWNTO 0));
  prelookup_comp_cast <= prelookup_comp_k(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp <= to_signed(16#0CCD#, 16) * prelookup_comp_cast;
  prelookup_comp_add_cast <= resize(prelookup_comp_mul_temp, 33);
  prelookup_comp_add_temp <= prelookup_comp_add_cast + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_1 <= prelookup_comp_add_temp(30 DOWNTO 15);
  prelookup_comp_sub_temp_1 <= In1_0 - prelookup_comp_sub_cast_1;
  prelookup_comp_cast_1 <= prelookup_comp_sub_temp_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_1 <= prelookup_comp_cast_1 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction1 <= to_unsigned(0, 32) WHEN (In1_0 = to_signed(-16#8000#, 16)) OR (In1_0 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_1(31 DOWNTO 0));
  prelookup_comp_index1 <= prelookup_comp_k;

  In1_1 <= signed(In1_signed(1));

  prelookup_comp_sub_cast_2 <= resize(In1_1, 17);
  prelookup_comp_sub_temp_2 <= prelookup_comp_sub_cast_2 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_2 <= prelookup_comp_sub_temp_2 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_1 <= to_unsigned(16#00#, 5) WHEN In1_1 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_1 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_2(4 DOWNTO 0));
  prelookup_comp_cast_2 <= prelookup_comp_k_1(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_1 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_2;
  prelookup_comp_add_cast_1 <= resize(prelookup_comp_mul_temp_1, 33);
  prelookup_comp_add_temp_1 <= prelookup_comp_add_cast_1 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_3 <= prelookup_comp_add_temp_1(30 DOWNTO 15);
  prelookup_comp_sub_temp_3 <= In1_1 - prelookup_comp_sub_cast_3;
  prelookup_comp_cast_3 <= prelookup_comp_sub_temp_3 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_3 <= prelookup_comp_cast_3 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction2 <= to_unsigned(0, 32) WHEN (In1_1 = to_signed(-16#8000#, 16)) OR (In1_1 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_3(31 DOWNTO 0));
  prelookup_comp_index2 <= prelookup_comp_k_1;

  In1_2 <= signed(In1_signed(2));

  prelookup_comp_sub_cast_4 <= resize(In1_2, 17);
  prelookup_comp_sub_temp_4 <= prelookup_comp_sub_cast_4 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_4 <= prelookup_comp_sub_temp_4 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_2 <= to_unsigned(16#00#, 5) WHEN In1_2 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_2 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_4(4 DOWNTO 0));
  prelookup_comp_cast_4 <= prelookup_comp_k_2(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_2 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_4;
  prelookup_comp_add_cast_2 <= resize(prelookup_comp_mul_temp_2, 33);
  prelookup_comp_add_temp_2 <= prelookup_comp_add_cast_2 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_5 <= prelookup_comp_add_temp_2(30 DOWNTO 15);
  prelookup_comp_sub_temp_5 <= In1_2 - prelookup_comp_sub_cast_5;
  prelookup_comp_cast_5 <= prelookup_comp_sub_temp_5 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_5 <= prelookup_comp_cast_5 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction3 <= to_unsigned(0, 32) WHEN (In1_2 = to_signed(-16#8000#, 16)) OR (In1_2 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_5(31 DOWNTO 0));
  prelookup_comp_index3 <= prelookup_comp_k_2;

  In1_3 <= signed(In1_signed(3));

  prelookup_comp_sub_cast_6 <= resize(In1_3, 17);
  prelookup_comp_sub_temp_6 <= prelookup_comp_sub_cast_6 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_6 <= prelookup_comp_sub_temp_6 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_3 <= to_unsigned(16#00#, 5) WHEN In1_3 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_3 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_6(4 DOWNTO 0));
  prelookup_comp_cast_6 <= prelookup_comp_k_3(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_3 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_6;
  prelookup_comp_add_cast_3 <= resize(prelookup_comp_mul_temp_3, 33);
  prelookup_comp_add_temp_3 <= prelookup_comp_add_cast_3 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_7 <= prelookup_comp_add_temp_3(30 DOWNTO 15);
  prelookup_comp_sub_temp_7 <= In1_3 - prelookup_comp_sub_cast_7;
  prelookup_comp_cast_7 <= prelookup_comp_sub_temp_7 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_7 <= prelookup_comp_cast_7 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction4 <= to_unsigned(0, 32) WHEN (In1_3 = to_signed(-16#8000#, 16)) OR (In1_3 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_7(31 DOWNTO 0));
  prelookup_comp_index4 <= prelookup_comp_k_3;

  In1_4 <= signed(In1_signed(4));

  prelookup_comp_sub_cast_8 <= resize(In1_4, 17);
  prelookup_comp_sub_temp_8 <= prelookup_comp_sub_cast_8 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_8 <= prelookup_comp_sub_temp_8 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_4 <= to_unsigned(16#00#, 5) WHEN In1_4 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_4 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_8(4 DOWNTO 0));
  prelookup_comp_cast_8 <= prelookup_comp_k_4(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_4 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_8;
  prelookup_comp_add_cast_4 <= resize(prelookup_comp_mul_temp_4, 33);
  prelookup_comp_add_temp_4 <= prelookup_comp_add_cast_4 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_9 <= prelookup_comp_add_temp_4(30 DOWNTO 15);
  prelookup_comp_sub_temp_9 <= In1_4 - prelookup_comp_sub_cast_9;
  prelookup_comp_cast_9 <= prelookup_comp_sub_temp_9 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_9 <= prelookup_comp_cast_9 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction5 <= to_unsigned(0, 32) WHEN (In1_4 = to_signed(-16#8000#, 16)) OR (In1_4 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_9(31 DOWNTO 0));
  prelookup_comp_index5 <= prelookup_comp_k_4;

  In1_5 <= signed(In1_signed(5));

  prelookup_comp_sub_cast_10 <= resize(In1_5, 17);
  prelookup_comp_sub_temp_10 <= prelookup_comp_sub_cast_10 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_10 <= prelookup_comp_sub_temp_10 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_5 <= to_unsigned(16#00#, 5) WHEN In1_5 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_5 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_10(4 DOWNTO 0));
  prelookup_comp_cast_10 <= prelookup_comp_k_5(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_5 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_10;
  prelookup_comp_add_cast_5 <= resize(prelookup_comp_mul_temp_5, 33);
  prelookup_comp_add_temp_5 <= prelookup_comp_add_cast_5 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_11 <= prelookup_comp_add_temp_5(30 DOWNTO 15);
  prelookup_comp_sub_temp_11 <= In1_5 - prelookup_comp_sub_cast_11;
  prelookup_comp_cast_11 <= prelookup_comp_sub_temp_11 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_11 <= prelookup_comp_cast_11 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction6 <= to_unsigned(0, 32) WHEN (In1_5 = to_signed(-16#8000#, 16)) OR (In1_5 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_11(31 DOWNTO 0));
  prelookup_comp_index6 <= prelookup_comp_k_5;

  In1_6 <= signed(In1_signed(6));

  prelookup_comp_sub_cast_12 <= resize(In1_6, 17);
  prelookup_comp_sub_temp_12 <= prelookup_comp_sub_cast_12 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_12 <= prelookup_comp_sub_temp_12 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_6 <= to_unsigned(16#00#, 5) WHEN In1_6 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_6 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_12(4 DOWNTO 0));
  prelookup_comp_cast_12 <= prelookup_comp_k_6(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_6 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_12;
  prelookup_comp_add_cast_6 <= resize(prelookup_comp_mul_temp_6, 33);
  prelookup_comp_add_temp_6 <= prelookup_comp_add_cast_6 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_13 <= prelookup_comp_add_temp_6(30 DOWNTO 15);
  prelookup_comp_sub_temp_13 <= In1_6 - prelookup_comp_sub_cast_13;
  prelookup_comp_cast_13 <= prelookup_comp_sub_temp_13 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_13 <= prelookup_comp_cast_13 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction7 <= to_unsigned(0, 32) WHEN (In1_6 = to_signed(-16#8000#, 16)) OR (In1_6 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_13(31 DOWNTO 0));
  prelookup_comp_index7 <= prelookup_comp_k_6;

  In1_7 <= signed(In1_signed(7));

  prelookup_comp_sub_cast_14 <= resize(In1_7, 17);
  prelookup_comp_sub_temp_14 <= prelookup_comp_sub_cast_14 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_14 <= prelookup_comp_sub_temp_14 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_7 <= to_unsigned(16#00#, 5) WHEN In1_7 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_7 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_14(4 DOWNTO 0));
  prelookup_comp_cast_14 <= prelookup_comp_k_7(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_7 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_14;
  prelookup_comp_add_cast_7 <= resize(prelookup_comp_mul_temp_7, 33);
  prelookup_comp_add_temp_7 <= prelookup_comp_add_cast_7 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_15 <= prelookup_comp_add_temp_7(30 DOWNTO 15);
  prelookup_comp_sub_temp_15 <= In1_7 - prelookup_comp_sub_cast_15;
  prelookup_comp_cast_15 <= prelookup_comp_sub_temp_15 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_15 <= prelookup_comp_cast_15 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction8 <= to_unsigned(0, 32) WHEN (In1_7 = to_signed(-16#8000#, 16)) OR (In1_7 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_15(31 DOWNTO 0));
  prelookup_comp_index8 <= prelookup_comp_k_7;

  In1_8 <= signed(In1_signed(8));

  prelookup_comp_sub_cast_16 <= resize(In1_8, 17);
  prelookup_comp_sub_temp_16 <= prelookup_comp_sub_cast_16 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_16 <= prelookup_comp_sub_temp_16 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_8 <= to_unsigned(16#00#, 5) WHEN In1_8 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_8 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_16(4 DOWNTO 0));
  prelookup_comp_cast_16 <= prelookup_comp_k_8(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_8 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_16;
  prelookup_comp_add_cast_8 <= resize(prelookup_comp_mul_temp_8, 33);
  prelookup_comp_add_temp_8 <= prelookup_comp_add_cast_8 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_17 <= prelookup_comp_add_temp_8(30 DOWNTO 15);
  prelookup_comp_sub_temp_17 <= In1_8 - prelookup_comp_sub_cast_17;
  prelookup_comp_cast_17 <= prelookup_comp_sub_temp_17 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_17 <= prelookup_comp_cast_17 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction9 <= to_unsigned(0, 32) WHEN (In1_8 = to_signed(-16#8000#, 16)) OR (In1_8 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_17(31 DOWNTO 0));
  prelookup_comp_index9 <= prelookup_comp_k_8;

  In1_9 <= signed(In1_signed(9));

  prelookup_comp_sub_cast_18 <= resize(In1_9, 17);
  prelookup_comp_sub_temp_18 <= prelookup_comp_sub_cast_18 - to_signed(-16#08000#, 17);
  prelookup_comp_div_temp_18 <= prelookup_comp_sub_temp_18 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_k_9 <= to_unsigned(16#00#, 5) WHEN In1_9 = to_signed(-16#8000#, 16) ELSE
      to_unsigned(16#13#, 5) WHEN In1_9 >= to_signed(16#7337#, 16) ELSE
      unsigned(prelookup_comp_div_temp_18(4 DOWNTO 0));
  prelookup_comp_cast_18 <= prelookup_comp_k_9(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_mul_temp_9 <= to_signed(16#0CCD#, 16) * prelookup_comp_cast_18;
  prelookup_comp_add_cast_9 <= resize(prelookup_comp_mul_temp_9, 33);
  prelookup_comp_add_temp_9 <= prelookup_comp_add_cast_9 + to_signed(-1073741824, 33);
  prelookup_comp_sub_cast_19 <= prelookup_comp_add_temp_9(30 DOWNTO 15);
  prelookup_comp_sub_temp_19 <= In1_9 - prelookup_comp_sub_cast_19;
  prelookup_comp_cast_19 <= prelookup_comp_sub_temp_19 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  prelookup_comp_div_temp_19 <= prelookup_comp_cast_19 / to_signed(16#0CCD#, 16);
  
  prelookup_comp_fraction10 <= to_unsigned(0, 32) WHEN (In1_9 = to_signed(-16#8000#, 16)) OR (In1_9 >= to_signed(16#7337#, 16)) ELSE
      unsigned(prelookup_comp_div_temp_19(31 DOWNTO 0));
  prelookup_comp_index10 <= prelookup_comp_k_9;

  prelookup_idx_sat(0) <= prelookup_comp_index1;
  prelookup_idx_sat(1) <= prelookup_comp_index2;
  prelookup_idx_sat(2) <= prelookup_comp_index3;
  prelookup_idx_sat(3) <= prelookup_comp_index4;
  prelookup_idx_sat(4) <= prelookup_comp_index5;
  prelookup_idx_sat(5) <= prelookup_comp_index6;
  prelookup_idx_sat(6) <= prelookup_comp_index7;
  prelookup_idx_sat(7) <= prelookup_comp_index8;
  prelookup_idx_sat(8) <= prelookup_comp_index9;
  prelookup_idx_sat(9) <= prelookup_comp_index10;

  saturate_output : PROCESS (prelookup_idx_sat)
  BEGIN

    FOR ii IN 0 TO 9 LOOP
      IF prelookup_idx_sat(ii) > to_unsigned(16#13#, 5) THEN 
        prelookup_idx(ii) <= to_unsigned(16#13#, 5);
      ELSE 
        prelookup_idx(ii) <= prelookup_idx_sat(ii);
      END IF;
    END LOOP;

  END PROCESS saturate_output;


  outputgen4: FOR k IN 0 TO 9 GENERATE
    prelookup_idx_1(k) <= std_logic_vector(prelookup_idx(k));
  END GENERATE;

  outputgen3: FOR k IN 0 TO 9 GENERATE
    interp_11_signed(k) <= signed(interp_11(k));
  END GENERATE;


  relopout_0_gen: FOR t_0 IN 0 TO 9 GENERATE
    
    relopout_0(t_0) <= '1' WHEN prelookup_idx(t_0) = to_unsigned(16#13#, 5) ELSE
        '0';
  END GENERATE relopout_0_gen;


  relopout_0_0 <= relopout_0(0);

  bias <= '1';

  adder_v <= '0' & '0' & '0' & '0' & bias;

  Q2_plus_one12_gen: FOR t_01 IN 0 TO 9 GENERATE
    Q2_plus_one12(t_01) <= prelookup_idx(t_01) + adder_v;
  END GENERATE Q2_plus_one12_gen;


  Q2_plus_one12_0 <= Q2_plus_one12(0);

  relopout_0_1 <= relopout_0(1);

  Q2_plus_one12_1 <= Q2_plus_one12(1);

  relopout_0_2 <= relopout_0(2);

  Q2_plus_one12_2 <= Q2_plus_one12(2);

  relopout_0_3 <= relopout_0(3);

  Q2_plus_one12_3 <= Q2_plus_one12(3);

  relopout_0_4 <= relopout_0(4);

  Q2_plus_one12_4 <= Q2_plus_one12(4);

  relopout_0_5 <= relopout_0(5);

  Q2_plus_one12_5 <= Q2_plus_one12(5);

  relopout_0_6 <= relopout_0(6);

  Q2_plus_one12_6 <= Q2_plus_one12(6);

  relopout_0_7 <= relopout_0(7);

  Q2_plus_one12_7 <= Q2_plus_one12(7);

  relopout_0_8 <= relopout_0(8);

  Q2_plus_one12_8 <= Q2_plus_one12(8);

  relopout_0_9 <= relopout_0(9);

  Q2_plus_one12_9 <= Q2_plus_one12(9);

  prelookup_idx_0 <= prelookup_idx(0);

  
  Q12_0 <= Q2_plus_one12_0 WHEN relopout_0_0 = '0' ELSE
      prelookup_idx_0;

  prelookup_idx_1_1 <= prelookup_idx(1);

  
  Q12_1 <= Q2_plus_one12_1 WHEN relopout_0_1 = '0' ELSE
      prelookup_idx_1_1;

  prelookup_idx_2 <= prelookup_idx(2);

  
  Q12_2 <= Q2_plus_one12_2 WHEN relopout_0_2 = '0' ELSE
      prelookup_idx_2;

  prelookup_idx_3 <= prelookup_idx(3);

  
  Q12_3 <= Q2_plus_one12_3 WHEN relopout_0_3 = '0' ELSE
      prelookup_idx_3;

  prelookup_idx_4 <= prelookup_idx(4);

  
  Q12_4 <= Q2_plus_one12_4 WHEN relopout_0_4 = '0' ELSE
      prelookup_idx_4;

  prelookup_idx_5 <= prelookup_idx(5);

  
  Q12_5 <= Q2_plus_one12_5 WHEN relopout_0_5 = '0' ELSE
      prelookup_idx_5;

  prelookup_idx_6 <= prelookup_idx(6);

  
  Q12_6 <= Q2_plus_one12_6 WHEN relopout_0_6 = '0' ELSE
      prelookup_idx_6;

  prelookup_idx_7 <= prelookup_idx(7);

  
  Q12_7 <= Q2_plus_one12_7 WHEN relopout_0_7 = '0' ELSE
      prelookup_idx_7;

  prelookup_idx_8 <= prelookup_idx(8);

  
  Q12_8 <= Q2_plus_one12_8 WHEN relopout_0_8 = '0' ELSE
      prelookup_idx_8;

  prelookup_idx_9 <= prelookup_idx(9);

  
  Q12_9 <= Q2_plus_one12_9 WHEN relopout_0_9 = '0' ELSE
      prelookup_idx_9;

  Q12(0) <= Q12_0;
  Q12(1) <= Q12_1;
  Q12(2) <= Q12_2;
  Q12(3) <= Q12_3;
  Q12(4) <= Q12_4;
  Q12(5) <= Q12_5;
  Q12(6) <= Q12_6;
  Q12(7) <= Q12_7;
  Q12(8) <= Q12_8;
  Q12(9) <= Q12_9;

  outputgen2: FOR k IN 0 TO 9 GENERATE
    Q12_10(k) <= std_logic_vector(Q12(k));
  END GENERATE;

  outputgen1: FOR k IN 0 TO 9 GENERATE
    interp_12_signed(k) <= signed(interp_12(k));
  END GENERATE;


  interval_gen: FOR t_02 IN 0 TO 9 GENERATE
    fQ2_minus_fQ1_sub_cast(t_02) <= resize(interp_12_signed(t_02), 17);
    fQ2_minus_fQ1_sub_cast_1(t_02) <= resize(interp_11_signed(t_02), 17);
    interval(t_02) <= fQ2_minus_fQ1_sub_cast(t_02) - fQ2_minus_fQ1_sub_cast_1(t_02);
  END GENERATE interval_gen;


  fraction_idx(0) <= prelookup_comp_fraction1;
  fraction_idx(1) <= prelookup_comp_fraction2;
  fraction_idx(2) <= prelookup_comp_fraction3;
  fraction_idx(3) <= prelookup_comp_fraction4;
  fraction_idx(4) <= prelookup_comp_fraction5;
  fraction_idx(5) <= prelookup_comp_fraction6;
  fraction_idx(6) <= prelookup_comp_fraction7;
  fraction_idx(7) <= prelookup_comp_fraction8;
  fraction_idx(8) <= prelookup_comp_fraction9;
  fraction_idx(9) <= prelookup_comp_fraction10;


  interp_gen: FOR t_03 IN 0 TO 9 GENERATE
    interval_times_frac_cast(t_03) <= signed(resize(fraction_idx(t_03), 33));
    interval_times_frac_mul_temp(t_03) <= interval(t_03) * interval_times_frac_cast(t_03);
    interval_times_frac_cast_1(t_03) <= interval_times_frac_mul_temp(t_03)(48 DOWNTO 0);
    interp(t_03) <= interval_times_frac_cast_1(t_03)(47 DOWNTO 32);
  END GENERATE interp_gen;



  ReplicaOfSource_out1_gen: FOR t_04 IN 0 TO 9 GENERATE
    ReplicaOfSource_out1(t_04) <= interp_11_signed(t_04) + interp(t_04);
  END GENERATE ReplicaOfSource_out1_gen;


  outputgen: FOR k IN 0 TO 9 GENERATE
    Out1(k) <= std_logic_vector(ReplicaOfSource_out1(k));
  END GENERATE;

END rtl;

